<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-5KB58OA" failures="1" tests="4" name="Personal loan" time="0.081" errors="0" timestamp="2024-03-18T22:56:16 IST">
  <testcase classname="test.day4" name="LoginAPIHomeLoan" time="0.012"/>
  <testcase classname="test.day1" name="Demo" time="0.015"/>
  <testcase classname="test.day2" name="ploan" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day2.ploan(day2.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ploan -->
  <testcase classname="test.day1" name="SecondTest" time="0.013"/>
  <testcase classname="test.day4" name="WebloginHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- WebloginHomeLoan -->
  <testcase classname="test.day4" name="MobileLoginHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- MobileLoginHomeLoan -->
</testsuite> <!-- Personal loan -->
